java:
    environment:
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        FEATURE_RESP_SOLICITOR_DETAILS: "true"
        DOCMOSIS_SERVICE_DEV_MODE_FLAG: "true"
        PDF_TEST_ENABLED: "true"

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
